targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: false
          # disallow_unrecognized_keys: true
          explicit_to_json: true
          include_if_null: false
