name: gguf
description: GGUF file parser (to support getting information from LLM models to be run with llama.cpp)
version: 0.1.0
repository: https://github.com/agilord/gguf

#executables:
#  gguf:

topics:
  - gguf
  - llamacpp
  - llama-cpp
  - llm

environment:
  sdk: '^3.9.0'

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.6.1
  huggingface_tools: ^0.1.0
  json_serializable: ^6.10.0
  lints: ^6.0.0
  path: ^1.9.1
  test: ^1.25.14
